import type { Metadata } from "next";
import { Geist, Geist_Mono, Syne, Almendra } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation/navigation";

const syneFont = Syne({
  subsets: ["latin"],
  weight: "600",
});

const almendraFont = Almendra({
  subsets: ["latin"],
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`mx-auto container px-4 ${almendraFont.className} antialiased`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
