import type { Metadata } from "next";
import { Geist, Geist_Mono, Syne, Almendra } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation/navigation";

const almendraFont = Almendra({
  subsets: ["latin"],
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${almendraFont.className} antialiased container mx-auto `}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
